# Generated by Django 4.1.6 on 2023-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
