# Generated by Django 4.1.6 on 2023-02-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0006_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Working', 'Working'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='ToDo', max_length=7),
        ),
    ]
