# Generated by Django 4.1.6 on 2023-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='member_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('UI/UX Design', 'UI/UX Design'), ('Product Owner', 'Product Owner'), ('Srum Master', 'Srum Master'), ('Testing', 'Testing')], default='Frontend', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Working', 'Working'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='ToDo', max_length=20),
        ),
    ]
