# Generated by Django 4.1.6 on 2023-02-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0010_alter_task_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_task',
            field=models.CharField(default='No subtask', max_length=10),
        ),
    ]
