# Generated by Django 4.1.6 on 2023-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0011_task_sub_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=50)),
                ('status_subtask', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
