# Generated by Django 4.1.6 on 2023-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0012_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='newCol',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
