# Generated by Django 4.1.6 on 2023-02-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0014_task_newcol2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='newCol',
        ),
        migrations.RemoveField(
            model_name='task',
            name='newCol2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_task',
        ),
    ]
