# Generated by Django 4.1.6 on 2023-02-05 11:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('prio', models.CharField(choices=[('1', 'Low'), ('2', 'Med'), ('3', 'Urg')], default=1, max_length=1)),
                ('member_type', models.CharField(choices=[('1', 'Frontend'), ('2', 'Backend'), ('3', 'UI/UX Design'), ('4', 'Product Owner'), ('5', 'Srum Master'), ('6', 'Testing')], default=1, max_length=1)),
                ('status', models.CharField(choices=[('1', 'ToDo'), ('2', 'Working'), ('3', 'Waiting'), ('4', 'Done')], default=1, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
